name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Fails
      run: false
    - name: Test
      run: ./gradlew check
    - name: Release
      if: ${{ github.ref == 'master' }}
      env:
        ALTER_BUGSNAG_KEY: ${{ secrets.ALTER_BUGSNAG_KEY }}
        ALTER_PUBLISHKEY_JSON_B64: ${{ secrets.ALTER_PUBLISHKEY_JSON_B64 }}
        ALTER_UPLOAD_KEY_B64: ${{ secrets.ALTER_UPLOAD_KEY_B64 }}
        ALTER_UPLOAD_KEY_PASSWORD: ${{ secrets.ALTER_UPLOAD_KEY_PASSWORD }}
        ALTER_UPLOAD_STORE_PASSWORD: ${{ secrets.ALTER_UPLOAD_STORE_PASSWORD }}
      run: |
        .github/workflows/setup_ci_env.sh
        ./gradlew :app:publishReleaseApk
