name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: |
        .github/workflows/setup_ci_env.sh
        ./gradlew test :app:publishReleaseApk
